development:
   theme_id: 163020233
   password: 64947c1fe154d4607e2ca5b341e585be
   store: https://quintushortus.myshopify.com
   timeout: 180s
   ignore_files:
       - config.yml
       - .gitignore
